language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# travis CI 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "chmod 700 gradlew \n ./gradlew clean build"

#CI 설정 완료시 메일로 알림   //
notifications:
  email:
    recipients:
      seongju99@naver.com